version: '3'
# Define common behavior
x-frontend:
  &default-frontend
  image: localhost:5000/frontend:latest
  build:
    context: .
    dockerfile: frontend.Dockerfile

x-backend:
  &default-backend
  image: localhost:5000/backend:latest
  build:
    context: .
    dockerfile: backend.Dockerfile 

services:
  frontend:
    *default-frontend
  version_tag_frontend:
    << : *default-frontend
    image: localhost:5000/frontend:${TAG}
  
  backend:
    *default-backend
  version_tag_backend:
    << : *default-backend
    image: localhost:5000/backend:${TAG}
